name: Exit silently on unsupported

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: voxpelli/ghatemplates/.github/workflows/exit-silently-on-unsupported.yml@main
    with:
      files: './cli-wrapper.cjs'
      node-versions: '12'
